import type { Process } from '../../types/process.types';

export const MOCK_SOLICITUD_PROCESSES: Process[] = [
  {
    id: 'SC-001',
    nombre: 'Contrato de prestación de servicios TI',
    etapa: 'EN_SOLICITUD',
    estado: 'Por asignar',
    origen: 'Solicitud',
    tipoProceso: 'Creación de contrato',
    tipoContrato: 'Prestación de servicios',
    plantillaSolicitud: 'Plantilla servicios TI',
    plantillaWorkflow: null,
    ultimaActualizacion: '13 feb 2025',
    solicitante: 'Amanda Rodríguez',
    asignadoA: null,
    fechaSolicitud: '10 feb 2025',
    tiempoRestanteGestion: '7 días hab.',
  },
  {
    id: 'SC-002',
    nombre: 'Renovación contrato arriendo oficinas',
    etapa: 'EN_SOLICITUD',
    estado: 'En curso',
    origen: 'Workflow',
    tipoProceso: 'Renovación de contrato',
    tipoContrato: 'Arriendo',
    plantillaSolicitud: 'Plantilla arriendo',
    plantillaWorkflow: null,
    ultimaActualizacion: '13 feb 2025',
    solicitante: 'Roberto Farías',
    asignadoA: 'Carolina Muñoz',
    fechaSolicitud: '08 feb 2025',
    tiempoRestanteGestion: '5 días hab.',
  },
  {
    id: 'SC-003',
    nombre: 'NDA con proveedor externo',
    etapa: 'EN_SOLICITUD',
    estado: 'Por asignar',
    origen: 'Solicitud',
    tipoProceso: 'Creación de contrato',
    tipoContrato: 'Confidencialidad',
    plantillaSolicitud: null,
    plantillaWorkflow: null,
    ultimaActualizacion: '12 feb 2025',
    solicitante: 'Amanda Rodríguez',
    asignadoA: null,
    fechaSolicitud: '09 feb 2025',
    tiempoRestanteGestion: '3 días hab.',
  },
  {
    id: 'SC-004',
    nombre: 'Adenda contrato suministro materiales',
    etapa: 'EN_SOLICITUD',
    estado: 'En curso',
    origen: 'Workflow',
    tipoProceso: 'Modificación de contrato',
    tipoContrato: 'Suministro',
    plantillaSolicitud: 'Plantilla suministro',
    plantillaWorkflow: null,
    ultimaActualizacion: '12 feb 2025',
    solicitante: 'Carlos Pérez',
    asignadoA: 'Roberto Farías',
    fechaSolicitud: '07 feb 2025',
    tiempoRestanteGestion: '2 días hab.',
  },
  {
    id: 'SC-005',
    nombre: 'Contrato de licenciamiento software ERP',
    etapa: 'EN_SOLICITUD',
    estado: 'Por asignar',
    origen: 'Solicitud',
    tipoProceso: 'Creación de contrato',
    tipoContrato: 'Licenciamiento',
    plantillaSolicitud: 'Plantilla licencias',
    plantillaWorkflow: null,
    ultimaActualizacion: '13 feb 2025',
    solicitante: 'Carolina Muñoz',
    asignadoA: null,
    fechaSolicitud: '11 feb 2025',
    tiempoRestanteGestion: '8 días hab.',
  },
  {
    id: 'SC-006',
    nombre: 'Contrato outsourcing contabilidad',
    etapa: 'EN_SOLICITUD',
    estado: 'En curso',
    origen: 'Solicitud',
    tipoProceso: 'Creación de contrato',
    tipoContrato: 'Outsourcing',
    plantillaSolicitud: 'Plantilla outsourcing',
    plantillaWorkflow: null,
    ultimaActualizacion: '11 feb 2025',
    solicitante: 'Roberto Farías',
    asignadoA: 'Amanda Rodríguez',
    fechaSolicitud: '06 feb 2025',
    tiempoRestanteGestion: 'Atrasado (2 días hab.)',
  },
  {
    id: 'SC-007',
    nombre: 'Contrato marco proveedor logístico',
    etapa: 'EN_SOLICITUD',
    estado: 'En curso',
    origen: 'Workflow',
    tipoProceso: 'Creación de contrato',
    tipoContrato: 'Marco',
    plantillaSolicitud: 'Plantilla marco',
    plantillaWorkflow: null,
    ultimaActualizacion: '10 feb 2025',
    solicitante: 'Carlos Pérez',
    asignadoA: 'Carolina Muñoz',
    fechaSolicitud: '05 feb 2025',
    tiempoRestanteGestion: '1 día hab.',
  },
  {
    id: 'SC-008',
    nombre: 'Término anticipado contrato soporte técnico',
    etapa: 'EN_SOLICITUD',
    estado: 'Por asignar',
    origen: 'Solicitud',
    tipoProceso: 'Término de contrato',
    tipoContrato: 'Soporte técnico',
    plantillaSolicitud: null,
    plantillaWorkflow: null,
    ultimaActualizacion: '13 feb 2025',
    solicitante: 'Amanda Rodríguez',
    asignadoA: null,
    fechaSolicitud: '12 feb 2025',
    tiempoRestanteGestion: '10 días hab.',
  },
  {
    id: 'SC-009',
    nombre: 'Contrato de arrendamiento bodega sur',
    etapa: 'FORMULARIO',
    estado: 'En borrador',
    origen: 'Solicitud',
    tipoProceso: 'Creación de contrato',
    tipoContrato: 'Arriendo',
    plantillaSolicitud: 'Plantilla arriendo',
    plantillaWorkflow: null,
    ultimaActualizacion: '13 feb 2025',
    solicitante: 'Carolina Muñoz',
    asignadoA: null,
    fechaSolicitud: '13 feb 2025',
    tiempoRestanteGestion: '–',
  },
  {
    id: 'SC-010',
    nombre: 'Renovación contrato mantención equipos',
    etapa: 'FORMULARIO',
    estado: 'En borrador',
    origen: 'Solicitud',
    tipoProceso: 'Renovación de contrato',
    tipoContrato: 'Mantención',
    plantillaSolicitud: 'Plantilla mantención',
    plantillaWorkflow: null,
    ultimaActualizacion: '12 feb 2025',
    solicitante: 'Roberto Farías',
    asignadoA: null,
    fechaSolicitud: '12 feb 2025',
    tiempoRestanteGestion: '–',
  },
];

export const MOCK_WORKFLOW_PROCESSES: Process[] = [
  {
    id: 'WF-001',
    nombre: 'Contrato prestación de servicios Magellan',
    etapa: 'EN_WORKFLOW',
    estado: 'En curso',
    origen: 'Workflow',
    tipoProceso: 'Creación de contrato',
    tipoContrato: 'Prestación de servicios',
    plantillaSolicitud: null,
    plantillaWorkflow: null,
    ultimaActualizacion: '13 feb 2025',
    pasoActual: '2. Formulario',
    responsablePasoActual: 'Alice Johnson',
    responsableInitials: 'AJ',
    fechaInicioPaso: '13 feb 2025',
    tiempoRestantePaso: 'Atrasado (11 días hab.)',
    tiempoRestanteTipo: 'atrasado',
    vencimientoPaso: '10 feb 2026',
  },
  {
    id: 'WF-002',
    nombre: 'Renovación contrato arriendo corporativo',
    etapa: 'EN_WORKFLOW',
    estado: 'Pausado',
    origen: 'Workflow',
    tipoProceso: 'Renovación de contrato',
    tipoContrato: 'Arriendo',
    plantillaSolicitud: null,
    plantillaWorkflow: 'Nombre de la plantilla',
    ultimaActualizacion: '13 feb 2025',
    pasoActual: '3. Resumen de solicitud',
    responsablePasoActual: 'Alice Johnson',
    responsableInitials: 'AJ',
    fechaInicioPaso: '13 feb 2025',
    tiempoRestantePaso: 'Pausado',
    tiempoRestanteTipo: 'pausado',
    vencimientoPaso: '17 feb 2026',
  },
  {
    id: 'WF-003',
    nombre: 'Adenda contrato suministro materiales',
    etapa: 'EN_WORKFLOW',
    estado: 'En curso',
    origen: 'Workflow',
    tipoProceso: 'Modificación de contrato',
    tipoContrato: 'Suministro',
    plantillaSolicitud: null,
    plantillaWorkflow: null,
    ultimaActualizacion: '13 feb 2025',
    pasoActual: '3. Resumen de solicitud',
    responsablePasoActual: 'Alice Johnson',
    responsableInitials: 'AJ',
    fechaInicioPaso: '13 feb 2025',
    tiempoRestantePaso: '3 días hab.',
    tiempoRestanteTipo: 'normal',
    vencimientoPaso: null,
  },
  {
    id: 'WF-004',
    nombre: 'Contrato marco proveedor logístico',
    etapa: 'EN_WORKFLOW',
    estado: 'En curso',
    origen: 'Workflow',
    tipoProceso: 'Creación de contrato',
    tipoContrato: 'Marco',
    plantillaSolicitud: null,
    plantillaWorkflow: 'Nombre de la plantilla',
    ultimaActualizacion: '13 feb 2025',
    pasoActual: '1. Redacción',
    responsablePasoActual: 'Daniel Lopez',
    responsableInitials: 'DL',
    fechaInicioPaso: '13 feb 2025',
    tiempoRestantePaso: '3 días hab.',
    tiempoRestanteTipo: 'normal',
    vencimientoPaso: '14 feb 2026',
  },
  {
    id: 'WF-005',
    nombre: 'NDA con consultoría externa',
    etapa: 'EN_WORKFLOW',
    estado: 'En curso',
    origen: 'Workflow',
    tipoProceso: 'Creación de contrato',
    tipoContrato: 'Confidencialidad',
    plantillaSolicitud: null,
    plantillaWorkflow: 'Nombre de la plantilla',
    ultimaActualizacion: '13 feb 2025',
    pasoActual: '3. Clasificación',
    responsablePasoActual: 'Zachary Taylor',
    responsableInitials: 'ZT',
    fechaInicioPaso: '13 feb 2025',
    tiempoRestantePaso: '1 día hab.',
    tiempoRestanteTipo: 'normal',
    vencimientoPaso: '20 feb 2026',
  },
  {
    id: 'WF-006',
    nombre: 'Término anticipado contrato soporte',
    etapa: 'EN_WORKFLOW',
    estado: 'En curso',
    origen: 'Workflow',
    tipoProceso: 'Término de contrato',
    tipoContrato: 'Soporte técnico',
    plantillaSolicitud: null,
    plantillaWorkflow: 'Nombre de la plantilla',
    ultimaActualizacion: '13 feb 2025',
    pasoActual: '3. Clasificación',
    responsablePasoActual: 'Brian Kim',
    responsableInitials: 'BK',
    fechaInicioPaso: '13 feb 2025',
    tiempoRestantePaso: '1 día hab.',
    tiempoRestanteTipo: 'normal',
    vencimientoPaso: '16 feb 2026',
  },
  {
    id: 'WF-007',
    nombre: 'Contrato de licenciamiento software ERP',
    etapa: 'EN_WORKFLOW',
    estado: 'Finalizado',
    origen: 'Workflow',
    tipoProceso: 'Creación de contrato',
    tipoContrato: 'Licenciamiento',
    plantillaSolicitud: null,
    plantillaWorkflow: 'Nombre de la plantilla',
    ultimaActualizacion: '13 feb 2025',
    pasoActual: '3. Clasificación',
    responsablePasoActual: 'Yasmine Patel',
    responsableInitials: 'YP',
    fechaInicioPaso: '13 feb 2025',
    tiempoRestantePaso: '1 día hab.',
    tiempoRestanteTipo: 'normal',
    vencimientoPaso: '20 feb 2026',
  },
  {
    id: 'WF-008',
    nombre: 'Renovación servicio mantención HVAC',
    etapa: 'EN_WORKFLOW',
    estado: 'En curso',
    origen: 'Workflow',
    tipoProceso: 'Renovación de contrato',
    tipoContrato: 'Mantención',
    plantillaSolicitud: null,
    plantillaWorkflow: null,
    ultimaActualizacion: '13 feb 2025',
    pasoActual: '3. Resumen de solicitud',
    responsablePasoActual: 'Ella Rodriguez',
    responsableInitials: 'ER',
    fechaInicioPaso: '13 feb 2025',
    tiempoRestantePaso: 'Atrasado (2 días hab.)',
    tiempoRestanteTipo: 'atrasado',
    vencimientoPaso: '10 feb 2026',
  },
];

export const MOCK_PROCESSES: Process[] = [
  {
    id: 'PC-001',
    nombre: 'Contrato de prestación de servicios TI',
    etapa: 'FORMULARIO',
    estado: 'En borrador',
    origen: 'Solicitud',
    tipoProceso: 'Creación de contrato',
    tipoContrato: 'Prestación de servicios',
    plantillaSolicitud: 'Plantilla servicios TI',
    plantillaWorkflow: null,
    ultimaActualizacion: '13 feb 2025',
  },
  {
    id: 'PC-002',
    nombre: 'Renovación contrato arriendo oficinas',
    etapa: 'EN_SOLICITUD',
    estado: 'Por asignar',
    origen: 'Workflow',
    tipoProceso: 'Renovación de contrato',
    tipoContrato: 'Arriendo',
    plantillaSolicitud: 'Plantilla arriendo',
    plantillaWorkflow: null,
    ultimaActualizacion: '13 feb 2025',
  },
  {
    id: 'PC-003',
    nombre: 'Adenda contrato suministro materiales',
    etapa: 'EN_WORKFLOW',
    estado: 'En curso',
    origen: 'Workflow',
    tipoProceso: 'Modificación de contrato',
    tipoContrato: 'Suministro',
    plantillaSolicitud: 'Plantilla suministro',
    plantillaWorkflow: 'Workflow aprobación',
    ultimaActualizacion: '13 feb 2025',
  },
  {
    id: 'PC-004',
    nombre: 'Contrato marco proveedor logístico',
    etapa: 'FINALIZADO',
    estado: 'Finalizado',
    origen: 'Workflow',
    tipoProceso: 'Creación de contrato',
    tipoContrato: 'Marco',
    plantillaSolicitud: 'Plantilla marco',
    plantillaWorkflow: 'Workflow firma digital',
    ultimaActualizacion: '13 feb 2025',
  },
  {
    id: 'PC-005',
    nombre: 'NDA con consultoría externa',
    etapa: 'EN_WORKFLOW',
    estado: 'En curso',
    origen: 'Workflow',
    tipoProceso: 'Creación de contrato',
    tipoContrato: 'Confidencialidad',
    plantillaSolicitud: null,
    plantillaWorkflow: 'Workflow legal',
    ultimaActualizacion: '13 feb 2025',
  },
  {
    id: 'PC-006',
    nombre: 'Término anticipado contrato soporte',
    etapa: 'FINALIZADO',
    estado: 'Finalizado',
    origen: 'Workflow',
    tipoProceso: 'Término de contrato',
    tipoContrato: 'Soporte técnico',
    plantillaSolicitud: null,
    plantillaWorkflow: null,
    ultimaActualizacion: '13 feb 2025',
  },
  {
    id: 'PC-007',
    nombre: 'Contrato de licenciamiento software ERP',
    etapa: 'FORMULARIO',
    estado: 'En borrador',
    origen: 'Solicitud',
    tipoProceso: 'Creación de contrato',
    tipoContrato: 'Licenciamiento',
    plantillaSolicitud: 'Plantilla licencias',
    plantillaWorkflow: null,
    ultimaActualizacion: '13 feb 2025',
  },
  {
    id: 'PC-008',
    nombre: 'Renovación servicio mantención HVAC',
    etapa: 'FORMULARIO',
    estado: 'En borrador',
    origen: 'Solicitud',
    tipoProceso: 'Renovación de contrato',
    tipoContrato: 'Mantención',
    plantillaSolicitud: 'Plantilla mantención',
    plantillaWorkflow: null,
    ultimaActualizacion: '13 feb 2025',
  },
  {
    id: 'PC-009',
    nombre: 'Contrato outsourcing contabilidad',
    etapa: 'FORMULARIO',
    estado: 'En borrador',
    origen: 'Solicitud',
    tipoProceso: 'Creación de contrato',
    tipoContrato: 'Outsourcing',
    plantillaSolicitud: 'Plantilla outsourcing',
    plantillaWorkflow: null,
    ultimaActualizacion: '13 feb 2025',
  },
  {
    id: 'PC-010',
    nombre: 'Adenda plazo contrato construcción',
    etapa: 'EN_SOLICITUD',
    estado: 'En borrador',
    origen: 'Solicitud',
    tipoProceso: 'Modificación de contrato',
    tipoContrato: 'Construcción',
    plantillaSolicitud: 'Plantilla construcción',
    plantillaWorkflow: null,
    ultimaActualizacion: '13 feb 2025',
  },
];
