import FileTypeUnknown from '../../assets/icons/unknown.svg';
import { themedStyled } from '../../themes';
import { SvgIcon } from '../svg-icon';

import { fileIconSvgMap } from './file-icon.utils';

import type { FileType } from './file-icon.interfaces';
import type { SvgIconProps } from '../svg-icon';
import type { StyleObject } from 'styletron-react';

interface FileIconProps extends Partial<Pick<SvgIconProps, 'width' | 'height'>> {
  fileExtension: FileType;
}

/** Styled file icon container */
const FileIconContainer = themedStyled<'div', { $style: StyleObject }>('div', ({ $style }) => ({
  display: 'flex',
  alignItems: 'center',
  ...$style,
}));

/**
 * Get the file icon given its extension, as an image generated by a pure SVG.
 *
 * @deprecated This component is deprecated due to the usage of outdated icons.
 * Please use FileTypeIcon instead.
 */
export const FileIcon = ({ fileExtension, width, height }: FileIconProps): JSX.Element => {
  const selectedFileIcon = fileIconSvgMap[fileExtension] || FileTypeUnknown;

  return (
    <FileIconContainer $style={{ width, height }}>
      <SvgIcon
        svg={selectedFileIcon}
        height={height}
        width={width}
      />
    </FileIconContainer>
  );
};
