export const QUICK_ACTION_MENU_WIDTH = '160px';

export const QUICK_ACTION_LIST_CONTAINER_WIDTH = '350px';

export const QUICK_ACTION_LIST_ITEM_HEIGHT = '70px';

export const QUICK_ACTION_LIST_CONTAINER_HEIGHT = '180px';

export const QUICK_ACTION_LIST_ITEM_TOOLTIP_WIDTH = '260px';
