/** NOTE: Some jsx-a11y rules are disabled because they are not relevant to the markdown components as they are generated by AI response. */
/* eslint-disable jsx-a11y/heading-has-content */
import { useEffect, useRef, useState } from 'react';

import { useMountedState } from 'react-use';

import { SectionedCard } from '@components/layouts';
import { Markdown } from '@components/markdown';
import { Text } from '@components/text';
import { noop } from '@utils/noop';

import { SUMMARY_CARD_MAX_HEIGHT } from '../../../data-extraction/components/data-extraction-beta/data-extraction-beta.constants';
import { useSectionedCardOverrides } from '../../../data-extraction/data-extraction.overrides';
import { ContractSummaryFooter } from '../contract-summary-footer';

import { textOverrides } from './contract-summary-detail-step.styles';

import type { ContractSummaryStepProps } from '../../contract-summary.types';

/**
 * ContractSummaryDetailStep component
 *
 * Displays a detailed view of a contract summary, including the summary text,
 * a copy button, and a footer with metadata.
 */
export const ContractSummaryDetailStep = ({
  'data-testid': dataTestId,
  contractSummary = '',
  contractSummaryUpdatedAt,
  zIndex,
  onClickBack = noop,
  onContractSummaryCopy = noop,
  onSummaryScroll = noop,
}: ContractSummaryStepProps): JSX.Element => {
  const { getSectionedCardOverrides } = useSectionedCardOverrides();

  const [summaryClipboardItem, setSummaryClipboardItem] = useState<ClipboardItem | undefined>(
    undefined,
  );

  const markdownRef = useRef<HTMLElement>(null);
  const isMounted = useMountedState();

  /**
   * Updates the `summaryClipboardItem` state when the `contractSummary` changes or
   * the `markdownRef` element is updated.
   *
   * Only performs the update if the component is mounted. This prevents errors
   * from trying to access DOM elements that no longer exist.
   */
  useEffect(() => {
    if (contractSummary !== '' && markdownRef.current && isMounted()) {
      const newClipboardItem = new ClipboardItem({
        'text/html': new Blob([markdownRef.current?.outerHTML || ''], { type: 'text/html' }),
      });

      setSummaryClipboardItem(newClipboardItem);
    }
  }, [isMounted, contractSummary]);

  return (
    <SectionedCard overrides={getSectionedCardOverrides({ maxHeight: SUMMARY_CARD_MAX_HEIGHT })}>
      <Text
        variant="bodySmall"
        color="neutralSubdued"
        overflow="auto"
        margin={0}
        as="span"
        overrides={textOverrides({
          dataTestId: `${dataTestId}--contract-summary-text`,
          onScroll: onSummaryScroll,
        })}
      >
        <span ref={markdownRef}>
          <Markdown
            extraComponents={{
              h1: <h4 />,
              h2: <h4 />,
              h3: <h4 />,
            }}
          >
            {contractSummary}
          </Markdown>
        </span>
      </Text>

      <ContractSummaryFooter
        summaryClipboardItem={summaryClipboardItem}
        contractSummary={contractSummary}
        contractSummaryUpdatedAt={contractSummaryUpdatedAt}
        data-testid={`${dataTestId}__footer`}
        zIndex={zIndex}
        onContractSummaryCopy={onContractSummaryCopy}
        onClickBack={onClickBack}
      />
    </SectionedCard>
  );
};
