import type { MutableRefObject } from 'react';

import type { TempAnswerParamsType } from './chat-bot-component.interface';
import type { AnswerReference } from './chat-message.interface';
import type { ChatBotNegativeFeedbackOption } from './webdox-ai.interfaces';
import type { GenerativeTextType } from '../../../interfaces/common.interfaces';
import type { FeedbackKind } from '../../feedback-button';

/** Unique string hash of the conversation */
export type GPTUniqueId = string;

export type ChatBotMessageKind = 'answer' | 'question';

export type ChatBotQuestionVariant =
  /** questions will not render and only their answers will render. */
  | 'placeholder'
  /** questions that persist in the chat bot conversation. */
  | 'persist'
  /** questions will be rendered but will not persist. */
  | 'temp';

export type ChatBotLoadingVariant =
  /** Front-only special styled message that will render a loading component */
  | 'loading'
  /** Front-only special styled message that will render a descriptive loading component */
  | 'descriptiveLoading';

export type ChatBotAnswerVariantV2 =
  | ChatBotLoadingVariant
  /** The main answer received from the Chat Bot directly */
  | 'persist'
  /** Used to indicate that the answer should render by chunks with a generative text */
  | 'generative'
  /** Front-only special styled message to update the current contract kind */
  | 'contractKind'
  /** Front-only special styled message to select 1 prompt from the the supplied list */
  | 'promptsSuggestions'
  /** Front-only special styled message with the first answer in the conversation when it is empty */
  | 'firstAnswer'
  /** Front-only special styled message that will render a system message */
  | 'systemAnswer'
  /** Front-only special styled message that will render an error message */
  | 'error';

export interface GPTBaseQuestion {
  /** Unique id used to render the messages component. Will never change, can be a locally generated or one from api */
  id: GPTUniqueId;
  /**
   * The unique id of the db stored record. Can mutate, but will not trigger a messages list record re add into the list.
   * If a record (question or answer) is loading, will be undefined
   */
  uuid?: GPTUniqueId;
  /** The string value body of the question or answer, in the user language */
  value: string;
  createdAt: string;
  updatedAt?: string;
  /** Will mark the current question or answer as loading, blocking further questions */
  isLoading?: boolean;
}

export interface ChatBotAnswerTypeV2 extends GPTBaseQuestion {
  variant: ChatBotAnswerVariantV2;
  kind?: 'error' | 'ok';
  /** Used only in the generative variant, required to render a portion of the text static */
  staticContent?: GenerativeTextType['accumulatedText'];
  feedback?: {
    /** Option selected for the negative feedback */
    predefinedOption?: ChatBotNegativeFeedbackOption;
    /** If not submitted feedback: undefined, otherwise the selected value */
    value?: FeedbackKind;
    /** A custom comment sometimes required in the feedback section */
    comment?: string;
  };
  /** All properties from special temporary answers (non-persisting ones) */
  tempProps?: TempAnswerParamsType;
  /** Indicates the references on which the answer is based. */
  references?: AnswerReference[];
}

export interface ChatBotQuestionTypeV2 extends GPTBaseQuestion {
  answers: ChatBotAnswerTypeV2[];
  /** Indicates if the current question is waiting for an answer generated by the Chat Bot */
  isWaiting?: boolean;
  /**
   * Indicates if the current question is a front-only or persisted.
   *
   * @defaultValue `persist`
   */
  variant: ChatBotQuestionVariant;
}

export interface GenerativeTextValueType extends GenerativeTextType {
  /** The latest chunk's position number, starting on 1 */
  latestPosition: number;
}

export type GenerativeAnswerChunkType = { text: string; position: number };

export type GenerativeAnswerType = {
  chunks: MutableRefObject<GenerativeAnswerChunkType[]>;
  isGenerating: boolean;
  isFinished: boolean;
};

export interface ChatBotConversationTypeV2 {
  id: GPTUniqueId;
  createdAt: string;
  updatedAt?: string;
  title: string;
  questions: ChatBotQuestionTypeV2[];
}
