import type { FileUploadItem } from '../file-upload-manager.interfaces';

export const mockFilesEveryType: FileUploadItem[] = [
  {
    id: '1',
    name: 'yearly-report.pdf',
    fileType: 'pdf',
    status: 'uploading',
    progress: 50,
    onClickAction: () => alert('Cancel upload'),
  },
  {
    id: '2',
    name: 'this-is-a-test-name-for-a-file-that-is-very-long-and-will-be-truncated.xlsx',
    fileType: 'xlsx',
    status: 'pending',
    onClickAction: () => alert('Cancel upload'),
  },
  {
    id: '3',
    name: 'presentation-deck.pptx',
    fileType: 'pptx',
    status: 'canceled',
  },
  {
    id: '4',
    name: 'presentation-project.pptx',
    fileType: 'pptx',
    status: 'completed',
    onClickAction: () => alert('View document'),
  },
  {
    id: '5',
    name: 'year-financial-analysis.xlsx',
    fileType: 'xlsx',
    status: 'rejected',
    reason: 'Timeout error',
    onClickAction: () => alert('Retry upload'),
  },
  {
    id: '6',
    name: 'month-financial-analysis.xlsx',
    fileType: 'xlsx',
    status: 'rejected',
    reason: 'File is corrupted',
  },
  {
    id: '7',
    name: 'contract-draft.docx',
    fileType: 'docx',
    status: 'omitted',
  },
  {
    id: '8',
    name: 'this-is-a-test-name-for-a-file-that-is-very-long-and-will-be-truncated-with-his-path.xlsx',
    path: 'folder/subfolder/long subfolder name/another folder name/this-is-a-test-name-for-a-file-that-is-very-long-and-will-be-truncated-with-his-path.xlsx',
    fileType: 'xlsx',
    status: 'pending',
  },
  {
    id: '9',
    name: 'file-9.txt',
    path: 'folder/subfolder/long subfolder name/another folder name/file-9.txt',
    fileType: 'txt',
    status: 'completed',
    onClickAction: () => alert('View document'),
  },
];

export const mockWithManyFiles: FileUploadItem[] = [
  {
    id: '6',
    name: 'Q4 Financial Report 2023.xlsx',
    fileType: 'xlsx',
    status: 'uploading',
    progress: 25,
  },
  {
    id: '7',
    name: 'Annual Budget 2024.xlsx',
    fileType: 'xlsx',
    status: 'completed',
  },
  {
    id: '8',
    name: 'Project Roadmap v2.pptx',
    fileType: 'pptx',
    status: 'pending',
  },
  {
    id: '9',
    name: 'Project Timeline.pptx',
    fileType: 'pptx',
    status: 'uploading',
    progress: 75,
  },
  {
    id: '10',
    name: 'Legal Agreement - Draft.docx',
    fileType: 'docx',
    status: 'pending',
  },
  {
    id: '11',
    name: 'Terms and Conditions.docx',
    fileType: 'docx',
    status: 'completed',
  },
  {
    id: '12',
    name: 'Security Audit 2024.pdf',
    fileType: 'pdf',
    status: 'rejected',
    reason: 'File is password protected',
  },
  {
    id: '13',
    name: 'Performance Analysis.pdf',
    fileType: 'pdf',
    status: 'omitted',
  },
  {
    id: '14',
    name: 'Marketing Assets.zip',
    fileType: 'zip',
    status: 'rejected',
    reason: 'File size exceeds 100MB limit',
  },
  {
    id: '15',
    name: 'Design Resources.zip',
    fileType: 'zip',
    status: 'uploading',
    progress: 50,
  },
  {
    id: '16',
    name: 'Employee Handbook 2024.pdf',
    fileType: 'pdf',
    status: 'pending',
  },
  {
    id: '17',
    name: 'Onboarding Checklist.docx',
    fileType: 'docx',
    status: 'completed',
  },
  {
    id: '18',
    name: 'Training Materials.pptx',
    fileType: 'pptx',
    status: 'uploading',
    progress: 10,
  },
  {
    id: '19',
    name: 'Sales Report Q1.xlsx',
    fileType: 'xlsx',
    status: 'rejected',
    reason: 'File is corrupted',
  },
  {
    id: '20',
    name: 'Marketing Strategy.pptx',
    fileType: 'pptx',
    status: 'completed',
  },
  {
    id: '21',
    name: 'System Architecture.pdf',
    fileType: 'pdf',
    status: 'uploading',
    progress: 90,
  },
  {
    id: '22',
    name: 'API Documentation v2.pdf',
    fileType: 'pdf',
    status: 'pending',
  },
  {
    id: '23',
    name: 'Database Schema.xlsx',
    fileType: 'xlsx',
    status: 'omitted',
  },
  {
    id: '24',
    name: 'Client Presentation.pptx',
    fileType: 'pptx',
    status: 'rejected',
    reason: 'Upload timeout',
  },
  {
    id: '25',
    name: 'Client Requirements.docx',
    fileType: 'docx',
    status: 'uploading',
    progress: 30,
  },
  {
    id: '26',
    name: 'Research Findings.pdf',
    fileType: 'pdf',
    status: 'completed',
  },
  {
    id: '27',
    name: 'Experiment Results.xlsx',
    fileType: 'xlsx',
    status: 'pending',
  },
  {
    id: '28',
    name: 'Patent Documentation.pdf',
    fileType: 'pdf',
    status: 'uploading',
    progress: 75,
  },
  {
    id: '29',
    name: 'Test Cases.xlsx',
    fileType: 'xlsx',
    status: 'rejected',
    reason: 'Invalid file format',
  },
  {
    id: '30',
    name: 'Bug Report Template.docx',
    fileType: 'docx',
    status: 'completed',
  },
  {
    id: '31',
    name: 'Operations Manual.pdf',
    fileType: 'pdf',
    status: 'pending',
  },
  {
    id: '32',
    name: 'Inventory Report.xlsx',
    fileType: 'xlsx',
    status: 'uploading',
    progress: 50,
  },
  {
    id: '33',
    name: 'Process Documentation.docx',
    fileType: 'docx',
    status: 'omitted',
  },
  {
    id: '34',
    name: 'Compliance Report 2024.pdf',
    fileType: 'pdf',
    status: 'rejected',
    reason: 'File contains malware',
  },
  {
    id: '35',
    name: 'Audit Checklist.xlsx',
    fileType: 'xlsx',
    status: 'completed',
  },
];
