/** NOTE: Some jsx-a11y rules are disabled because they are not relevant to the markdown components as they are generated by AI response. */
/* eslint-disable jsx-a11y/anchor-has-content */
/* eslint-disable jsx-a11y/alt-text */
/* eslint-disable jsx-a11y/anchor-is-valid */
/* eslint-disable jsx-a11y/heading-has-content */
import { useCss } from '@components/utils/hooks/use-css';

import { styles } from '../markdown.styles';

import type { MarkdownComponents } from '../markdown.interfaces';

/**
 * Map of markdown elements to React components, enabling customized styling and
 * behavior for each element.
 */
export const useMarkdownComponents = (): MarkdownComponents => {
  const {
    imgStyles,
    preStyles,
    codeStyles,
    blockquoteStyles,
    tableStyles,
    tableHeaderStyles,
    tableCellStyles,
  } = useCss(styles);

  return {
    // Headings
    h1: <h1 />,
    h2: <h2 />,
    h3: <h3 />,
    h4: <h4 />,
    h5: <h5 />,
    h6: <h6 />,

    // Text formatting
    p: <p />,
    strong: <strong />,
    em: <em />,
    u: <u />,
    del: <del />,
    blockquote: <blockquote className={blockquoteStyles} />,
    code: <code className={codeStyles} />,
    pre: <pre className={preStyles} />,

    // Links and images
    a: <a />,
    img: <img className={imgStyles} />,

    // Lists
    ul: <ul />,
    ol: <ol />,
    li: <li />,

    // Tables
    table: <table className={tableStyles} />,
    thead: <thead />,
    tbody: <tbody />,
    tr: <tr />,
    th: <th className={tableHeaderStyles} />,
    td: <td className={tableCellStyles} />,

    // Additional elements
    hr: <hr />, // Horizontal rule
    br: <br />, // Line break

    // Adding support for SVGs could be important for some markdown documents
    svg: <svg />,
    path: <path />,

    // Support for custom elements like span for inline styles or classes
    span: <span />,

    // Other semantic elements
    figure: <figure />,
    figcaption: <figcaption />,

    // Add more custom components as needed
  };
};
