export const POPOVER_CONTENT_WIDTH = '420px';

export const POPOVER_CONTENT_HEIGHT = '410px';

export const VIRTUALIZED_LIST_OVERSCAN = 5;

export const VIRTUALIZED_LIST_ITEM_ESTIMATE_SIZE = 41;

export const LIST_ITEM_HEIGHT = `${VIRTUALIZED_LIST_ITEM_ESTIMATE_SIZE}px`;
